version: '3'

services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx-cont
    build:
      context: ./requirements/nginx/
      args:
        UID: 1001
        GID: 1001
    networks:
      frontend:
        aliases:
          - ${DOMAIN_NAME}
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - NGINX_HOST_PORT=${NGINX_HOST_PORT}
    ports:
      - '${NGINX_HOST_PORT}:443'
    volumes:
      - ${CERTS_}:/etc/nginx/ssl
      - wp_vol:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always

  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb-cont
    build: ./requirements/mariadb
    networks:
      - backend
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_WORDPRESS_DATABASE=${MYSQL_WORDPRESS_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always

  wordpress:
    container_name: ${COMPOSE_PROJECT_NAME}-wordpress-cont
    build:
      context: ./requirements/wordpress/
      args:
        UID: 1002
        GID: 1002
    networks:
      - frontend
      - backend
      - cache
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_WORDPRESS_DATABASE=${MYSQL_WORDPRESS_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_USER_PASSWORD=${WORDPRESS_USER_PASSWORD}
      - WORDPRESS_USER_EMAIL=${WORDPRESS_USER_EMAIL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - wp_vol:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "docker-healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: always

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis-cont
    build: ./requirements/bonus/redis
    networks:
     - cache
    environment:
     - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_vol:/var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always

  ftp:
    container_name: ${COMPOSE_PROJECT_NAME}-ftp-cont
    build:
      context: ./requirements/bonus/ftp/
      args:
        UID: 1002
        GID: 1002
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ${CERTS_}:/etc/ssl/private
      - wp_vol:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always

networks:
  frontend:
    name: ${COMPOSE_PROJECT_NAME}-front.link
  backend:
    name: ${COMPOSE_PROJECT_NAME}-back.link
  cache:
    name: ${COMPOSE_PROJECT_NAME}-cache.link

volumes:
  wp_vol:
    name: wordpress_data
    driver: local
  db_vol:
    name: database_data
    driver: local
  redis_vol:
    name: redis_data
    driver: local
